services:
  - type: web
    name: turkyan-panel
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan migrate --force
    startCommand: apache2-foreground
    envVars:
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql.freedb.tech
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: freedb_turkyan-panel
      - key: DB_USERNAME
        value: freedb_turkyan-user
      - key: DB_PASSWORD
        value: 7b%Um$r37WgU&cb
      - key: NODE_VERSION
        value: 20
