services:
  - type: web
    name: turkyan-panel
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
